services:

  erpnext-image: &erpnext_image
    image: mabecenter/erpnext:0.0.1-2814e82
    platform: linux/amd64
    pull_policy: always
      
  backend:
    <<: *erpnext_image
    depends_on:
      configurator:
        condition: service_completed_successfully
    networks:
      bench-network: null
      mariadb-network: null
    platform: linux/amd64
    pull_policy: always
    restart: always 
    user: "1000:1000"
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume:
        nocopy: true
  configurator:
    <<: *erpnext_image
    command:
    - |
      ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE"; bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio "redis://$$REDIS_QUEUE"; bench set-config -gp socketio_port $$SOCKETIO_PORT;
    depends_on:
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
    entrypoint:
    - bash
    - -c
    environment:
      DB_HOST: mariadb-database
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    networks:
      bench-network: null
      mariadb-network: null
    platform: linux/amd64
    pull_policy: always
    user: "1000:1000"
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  frontend:
    <<: *erpnext_image
    command:
    - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: sync.mabecenter.org
      PROXY_READ_TIMEOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    labels:
      traefik.docker.network: traefik-public
      traefik.enable: "true"
      traefik.http.routers.erpnext-one-http.entrypoints: http
      traefik.http.routers.erpnext-one-http.middlewares: https-redirect
      traefik.http.routers.erpnext-one-http.rule: Host(`sync.mabecenter.org`)
      traefik.http.routers.erpnext-one-http.service: erpnext-one
      traefik.http.routers.erpnext-one-https.entrypoints: https
      traefik.http.routers.erpnext-one-https.rule: Host(`sync.mabecenter.org`)
      traefik.http.routers.erpnext-one-https.service: erpnext-one
      traefik.http.routers.erpnext-one-https.tls: "true"
      traefik.http.routers.erpnext-one-https.tls.certresolver: le
      traefik.http.services.erpnext-one.loadbalancer.server.port: "8080"
    extra_hosts:
      - "sync.mabecenter.org:host-gateway"
      - "relay.mabecenter.org:192.168.99.114"
    user: "1000:1000"
    networks:
      bench-network: null
      traefik-public: null
    platform: linux/amd64
    pull_policy: always
    restart: always 
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  queue-long:
    <<: *erpnext_image
    command:
    - bench
    - worker
    - --queue
    - long,default,short
    depends_on:
      configurator:
        condition: service_completed_successfully
    networks:
      bench-network: null
      mariadb-network: null
    platform: linux/amd64
    pull_policy: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  queue-short:
    <<: *erpnext_image
    command:
    - bench
    - worker
    - --queue
    - short,default
    depends_on:
      configurator:
        condition: service_completed_successfully
    networks:
      bench-network: null
      mariadb-network: null
    platform: linux/amd64
    pull_policy: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  redis-cache:
    image: redis:6.2-alpine
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: redis-cache-data
      target: /data
      volume: {}
  redis-queue:
    image: redis:6.2-alpine
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: redis-queue-data
      target: /data
      volume: {}
  scheduler:
    <<: *erpnext_image
    command:
    - bench
    - schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
    networks:
      bench-network: null
      mariadb-network: null
    platform: linux/amd64
    pull_policy: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  websocket:
    <<: *erpnext_image
    command:
    - node
    - /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      configurator:
        condition: service_completed_successfully
    networks:
      bench-network: null
      mariadb-network: null
    platform: linux/amd64
    pull_policy: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    extra_hosts:
      - "sync.mabecenter.org:host-gateway"
  create-site:
    <<: *erpnext_image
    networks:
      bench-network: null
      mariadb-network: null
    deploy:
      restart_policy:
        condition: none
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    entrypoint:
      - bash
      - -c
    command:
      - >
        bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=changeit --admin-password changeit --set-default sync.mabecenter.org;
        bench use sync.mabecenter.org;
        bench install-app company_sync --force;
        bench build --app frappe --hard-link --production;
        bench build --app company_sync --hard-link --production;
        bench migrate;
        bench clear-cache;
        bench clear-website-cache;
        bench enable-scheduler;
    env_file:
      - stack.env
  populate-assets:
    <<: *erpnext_image
    entrypoint: ["sh", "-c"]
    command:
      - >
        cp -fR /usr/share/nginx/html/assets /data;
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
networks:
  bench-network:
    name: erpnext-one
  mariadb-network:
    name: mariadb-network
    external: true
  traefik-public:
    name: traefik-public
    external: true
volumes:
  redis-cache-data:
    name: erpnext-one_redis-cache-data
  redis-queue-data:
    name: erpnext-one_redis-queue-data
  sites:
    name: erpnext-one_sites
x-backend-defaults:
  <<: *erpnext_image
  depends_on:
    configurator:
      condition: service_completed_successfully
  pull_policy: always
  volumes:
  - sites:/home/frappe/frappe-bench/sites
x-customizable-image:
  <<: *erpnext_image
  pull_policy: always
x-depends-on-configurator:
  depends_on:
    configurator:
      condition: service_completed_successfully
